### ISSUE TITLE
interview on the OpenCage Data blog about OSM in the Ukraine

### ISSUE THREAD

**Issue by freyfogle** [osm-ua/openstreetmap.org.ua#17]
Following up from our twitter conversation: 
https://twitter.com/osm_ua/status/708577644263174144

Many thanks for agreeing to do an interview on our blog!

I hope it leads to more contributors and more awareness of OSM.

Below are some questions, feel free to modify as you think best.

Please send any relevant photos, for example of local mapping parties or such. Don't worry if English is not perfect, I am happy to review and fix any typos.

You can see past interviews here to get an idea
http://blog.opencagedata.com/tagged/countryprofile

Many thanks!
1. Who are you and what do you do? What got you into OpenStreetMap?
2. What would you say is the current state of OSM and the OSM community in XXX?
3. What are the unique challenges and pleasures of OpenStreetMap in XXX? What aspects of the projects should the rest of the world be aware of?
4. What is the best way to get involved? Are you looking for remote support or trying to get locals as your primary mappers?
5. What steps could the global OpenStreetMap community take to help support OSM in XXX?
6. In 2014 OSM celebrated its 10th birthday. Where do you think the project will be in 10 years time, both globally and in XXX specifically?

**Comment by Kilkenni** [comment]
1. Hi, I'm Kilkenni, an Ukrainian mapper from Kyiv. My profile is available at http://hdyc.neis-one.org/?Kilkenni . Part time programmer novice, part time amateur FOSS evangelist with interests laying in local history, culture, street art, urban trips, bicycles, design and industrial zones, it was only natural I got interested in OSM. My participation in the project started when I first visited Kyiv and was looking for an Android map that could work locally on a standalone device without internet connection. OSM was the only choice at the time, so you may say it was fate :)
2. OSM in Ukraine is greatly underdeveloped. Unfortunately the project currently lacks publicity and media support, moving forward mostly due to local fans and their initiative. Ukraine has a great potential in OSM, being one of the leaders in IT outsourcing. Several well-known instruments, like Leaflet, are created by ukrainians, yet OSM still remains a thing for enthusiasts, which is sad.
   The community in UA is currently fractured and hard to get together (yes, I'm talking about you, mapping-party-haters!). It has several great mappers, but not enough novices to develop properly. On the other hand, quality of the map varies greatly, there are lots of places to map and improve, even inside Kyiv. Which is great - you can quickly see the changes and feel that you make a difference.
3. One unique pleasure of Ukrainian OSM is its multi-lingual nature. Official language in Ukraine is Ukrainian, but Russian, Crimean Tatar, Polish, English, German and even Greek are also present. Ukraine is a big multinational pot rich with the history of strife, so many places have names in at least two languages. That led to streets being mapped with relations, which, while questionable in terms of data structure, allows maintaining localization quite easily.
   Another pleasure is that Ukraine has lots of talented programmers and web designers, who, while divided and quite anarchically "organized", come up with different great ideas. I suppose some people can tell about it much better than I, but to name a few, it's the local volunteer network. While traditionally strong, it's new to mapping, but already uses OSM in several tasks, albeit one always wishes for more.
   Yet another great opportunity I see is a total rebuilding of the government structures. It may seem tedious to some, but it's also a great time to push OSM further and establish useful ties and cooperation with new government structures, getting official gov data and integrating OSM-based FOSS solutions on the global level. While there is currently little progress, a window of opportunity is still there, and I'm very excited about any and all examples of such cooperation.
   Another interesting feature is the ongoing decommunization. Lots of geographic objects are renamed every month, and Ukrainian OSM users, in addition to mapping them, take place in public discussions.
   The unique challenge that pops to mind almost instantly is, of course, the war. The war dictates its own "traits". There's a demarcation line which OSCE tries to keep demilitarized, and which is literally dangerous to live in, let alone map. Then there's the occupied territory where Ukrainian and Crimean Tatar languages are repressed, including in geographical names. Then there's Crimea, which obviously becomes a target of information war, not only in media, but also in maps, leading to edit warring (which subsequently often leads to broken state borders since most "map combatants" are only vaguely familiar with OSM mapping. A surprise, isn't it? :). The "core OSM community" on both sides is, on the other hand, much more calm and tends to find compromises in what they do, which gives me great hope and inspiration. Then there's the actual warzone, which raises questions on its own since combatants from both sides are known to use OSM. Is it morally right to map a combat zone? Is it right to map military objects? Is it right to map infrastucture? It can be used by both civilians, including volunteers, and by combatants. It's not everyday we face these problems, but mapping in Ukraine has these challenges, and every single mapper finds his own answer.

--to be concluded

**Comment by Kilkenni** [comment]
- Go out and map! Just kidding, mapping in Ukraine often means that you need to map something remotely first, laying the street network and building outlines, then checking them on the ground, adding addresses, features (like building:material and levels), poi etc. I've noted that as the time passed I got to map more on the mobile devices (Vespucci) then in JOSM. Mobile editors are a great thing to get involved in everyday and spontaneous mapping: you can map when waiting for a friend or riding in a bus. Editors still have a long way to go (for example, in terms of usability), but using them is great.
  As for my own mapping techniques, I tend to map remotely at any place interesting to me at the moment, grabbing any free resource I can get my hands on (bing + mapbox + Mapillary + Yandex Panoramas? Easy!), but I also tend to do "mapping walks" when I feel like it. Getting locals is hard since active mappers are obviously mostly situated in big cities.
- Anything I can think about is (surprise!) SOTM in Ukraine. Not necessarily in Kyiv, there are other IT centers out there, but, if done right, it would be great in terms of public and media attention.
  Other than that, I feel OSM lacks ready solutions and how-to guidelines for business. It's often hard for me to propose it, because in many cases OSM needs software instruments for easy integration and scaling. For example, how about ready to use multilingual map support changing label language on the fly? How about forum-ready maps? MapBBCode is great, but it needs more distribution, more successful cases to refer to when you propose it. OSM needs to be less "a map for geeks" and more "a map for people". There are lots of "uncharted territories" ;) And that's not something a person (or even a local community) can handle on its own.
- I don't know where it will be. I can only hope it will be where I see it. A widely accepted standart for free geographical info, used by both governments and simple people. A better structurized database with better instruments to use it anywhere. A map that can give you answer for any geographical question. The thing that, along the other great things, makes electronic government real, gives us better control over out surroundings, more freedom, more opportunities and, ultimately, makes life better for all of us.

**Comment by freyfogle** [comment]
fantastic. I am travelling right now, but will publish tomorrow. 

Many thanks, I hope it leads to more contributors!

**Comment by Kilkenni** [comment]
Thanks for your kind words :) Maybe others can add more things to give a more complex and complete picture.

**Comment by freyfogle** [comment]
The interview is now live: http://blog.opencagedata.com/post/141155407748/country-profile-openstreetmap-in-the-ukraine Thanks again, really likes the answers - have to admit I had not considered the mapping implications of decommunization
